### ISSUE TITLE
[ERROR] with robot_description 

### ISSUE THREAD

**Issue by BonJohnLee** [DeepRoboticsLab/URDF_model#1]
![image](https://github.com/DeepRoboticsLab/URDF_model/assets/128108018/cb108204-290a-40a4-9fdb-2b7f972745ef)
在新创建的工作空间中，运行如下指令：
```shell
roslaunch lite3_description lite3_rviz
```
终端报错显示是
```
ERROR: cannot launch node of type [joint_state_publisher_gui/joint_state_publisher_gui]: joint_state_publisher_gui
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/slam/lite3/src
ROS path [2]=/opt/ros/melodic/share
```

**Comment by geekflyfly** [comment]
你电脑里可能缺少相关插件，  试试 sudo apt-get install ros-melodic-joint-state-publisher-gui    ， 另外建议执行 roslaunch lite3_description lite3_rviz.launch
